version: '3'
services:
  proxy:
    image: jwilder/nginx-proxy
    ports:
     - "80:80"
    volumes: 
     - /var/run/docker.sock:/tmp/docker.sock:ro

  geoserver:
    image: mbaussier/inao_geoserver:latest
    restart: on-failure
    environment:
     - VIRTUAL_HOST=geoserver.sig-inao.fr
    volumes:
     - /home/geoserver/config:/opt/geoserver/data_dir
  
  app:
    image: mbaussier/inao_app:latest
    restart: on-failure
    environment:
     - VIRTUAL_HOST=sig-inao.fr
    volumes: 
     - /home/app/config:/home/Inao_app/config
